### ISSUE TITLE
JustWrite-4.1.0（Windows）使用反馈

### ISSUE THREAD

**Issue by siyuhong** [yueshutong/JustWrite#3]
打开 .md文件 无法及时加载，需要在文件中选择打开才可接着 .md文件

**Comment by yueshutong** [comment]
是的，确实没做直接使用该软件打开md文件这个功能，下个版本会有的。

**Comment by siyuhong** [comment]
期待你的下一版，嘿嘿




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"薛勤"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月26日(星期二) 下午4:58
收件人:&nbsp;"yueshutong/JustWrite"<JustWrite@noreply.github.com&gt;;
抄送:&nbsp;"曾听风言"<1097201863@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yueshutong/JustWrite] JustWrite-4.1.0（Windows）使用反馈 (#3)




是的，确实没做直接使用该软件打开md文件这个功能，下个版本会有的。
