### ISSUE TITLE
windows不显示图片、mac相对路径不行

### ISSUE THREAD

**Issue by dataiyangu** [yueshutong/JustWrite#7]
这个软件对我非常有用，今天晚上刚开始用，发现
1.mac 中用typora中设置的相对路径是   images/xxx.png这种就不行   好像 ./images/xxx.png就可以了，但是typora不能设置成 前面有./这种
2.windows中图片不显示，相对路径、绝对路径都不行
windows上传到csdn失败（有图片的时候不行，没有图片的时候可以成功）
希望大佬修复下，感谢感谢，哪怕后期收费也行，别太贵就好，哈哈哈哈哈哈哈。

**Comment by yueshutong** [comment]
已修复
